version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: meu-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: Soleo # Opcional: defina um usuário root
      MONGO_INITDB_ROOT_PASSWORD: 1223334444 # Opcional: defina uma senha root
volumes:
  mongo-data: