import type { Product } from './CartContext';

export const allMockProducts: Product[] = [
  { id: '1', name: 'Tapete de Yoga Premium Conforto', price: 'R$ 199,90', iconPlaceholder: '🧘', description: 'Conforto e aderência para sua prática diária.' },
  { id: '2', name: 'Vela Aromática de Lavanda Relax', price: 'R$ 49,90', iconPlaceholder: '🕯️', description: 'Relaxe com o aroma suave da lavanda pura.' },
  { id: '3', name: 'Sino Tibetano para Meditação Zen', price: 'R$ 179,90', iconPlaceholder: '🎶', description: 'Som puro para harmonia e meditação profunda.' },
  { id: '4', name: 'Kit Incensos Naturais Purificantes', price: 'R$ 89,90', iconPlaceholder: '🌿', description: 'Variedade de aromas para purificar o ambiente.' },
  { id: '5', name: 'Garrafa com Cristal Quartzo Rosa', price: 'R$ 139,90', iconPlaceholder: '💧', description: 'Energize sua água com a vibração do amor.' },
  { id: '6', name: 'Livro: Guia de Yoga para Iniciantes', price: 'R$ 59,90', iconPlaceholder: '📚', description: 'Guia completo para começar sua jornada no yoga.' },
  { id: '7', name: 'Chá Calmante de Camomila Orgânico', price: 'R$ 29,90', iconPlaceholder: '🍵', description: 'Mistura orgânica para noites tranquilas e serenas.' },
  { id: '8', name: 'Japamala 108 Contas Rudraksha Sagrada', price: 'R$ 119,90', iconPlaceholder: '💎', description: 'Para meditação, foco e entoação de mantras.' },
  { id: '9', name: 'Almofada de Meditação Zafu Confort', price: 'R$ 159,90', iconPlaceholder: '🧘‍♀️', description: 'Suporte ideal para longas sessões de meditação.' },
  { id: '10', name: 'Óleo Essencial Puro Eucalipto', price: 'R$ 35,90', iconPlaceholder: '🍃', description: 'Refrescante e revigorante para aromaterapia eficaz.' },
  { id: '11', name: 'Fonte de Água Decorativa Zen Garden', price: 'R$ 299,90', iconPlaceholder: '⛲', description: 'Som relaxante de água para seu ambiente de paz.' },
  { id: '12', name: 'Canga Indiana Estampada Floral', price: 'R$ 75,00', iconPlaceholder: '🌸', description: 'Multiuso: praia, yoga, piquenique, decoração vibrante.' },
  { id: '13', name: 'Pedra Selenita Branca Purificadora', price: 'R$ 45,00', iconPlaceholder: '🤍', description: 'Para limpeza energética profunda e paz interior.' },
  { id: '14', name: 'Spray Energético de Alecrim Fresco', price: 'R$ 55,90', iconPlaceholder: '✨', description: 'Renove as energias do seu espaço com frescor.' },
  { id: '15', name: 'Kit Pedras dos 7 Chakras Alinhamento', price: 'R$ 129,00', iconPlaceholder: '🌈', description: 'Para alinhamento e equilíbrio completo dos chakras.' },
  { id: '16', name: 'Difusor Ultrassônico de Aromas Wood', price: 'R$ 220,00', iconPlaceholder: '💨', description: 'Umidifica e perfuma o ambiente suavemente.' },
  { id: '17', name: 'Rolo de Massagem Miofascial Pro', price: 'R$ 95,00', iconPlaceholder: '💪', description: 'Libere a tensão muscular e melhore a circulação.' },
  { id: '18', name: 'Buda Decorativo em Resina Dourado', price: 'R$ 110,00', iconPlaceholder: '🗿', description: 'Estátua serena para inspirar tranquilidade e foco.' },
  { id: '19', name: 'Pulseira dos 7 Chakras com Lava', price: 'R$ 65,00', iconPlaceholder: '💫', description: 'Equilíbrio e proteção energética no seu dia a dia.' },
  { id: '20', name: 'Incenso Natural de Palo Santo (Maço)', price: 'R$ 45,00', iconPlaceholder: '🪵', description: 'Madeira sagrada para purificação e boas vibrações.' },
  { id: '21', name: 'Bola de Massagem Cravo Relaxante', price: 'R$ 25,00', iconPlaceholder: '🔵', description: 'Ideal para aliviar pontos de tensão nos pés e mãos.' },
  { id: '22', name: 'Neti Pot Cerâmico para Limpeza Nasal', price: 'R$ 69,90', iconPlaceholder: '👃', description: 'Tradição ayurvédica para saúde respiratória.' },
  { id: '23', name: 'Diário de Gratidão com Capa Inspiradora', price: 'R$ 49,00', iconPlaceholder: '📓', description: 'Cultive a gratidão e transforme sua perspectiva.' },
  { id: '24', name: 'Moringa de Cerâmica Artesanal Paz', price: 'R$ 85,00', iconPlaceholder: '🏺', description: 'Mantenha sua água fresca com estilo e significado.' },
  { id: '25', name: 'CD de Músicas para Meditação e Relaxamento', price: 'R$ 39,90', iconPlaceholder: '💿', description: 'Trilhas sonoras para aprofundar seu estado meditativo.' },
  { id: '26', name: 'Escalda Pés Revigorante com Ervas', price: 'R$ 32,00', iconPlaceholder: '🦶', description: 'Relaxamento profundo e alívio para pés cansados.' },
  { id: '27', name: 'Luminária de Sal do Himalaia Autêntica', price: 'R$ 149,00', iconPlaceholder: '💡', description: 'Purifica o ar e cria uma atmosfera acolhedora.' },
  { id: '28', name: 'Orgonite Pirâmide Proteção Energética', price: 'R$ 99,00', iconPlaceholder: '🔺', description: 'Transmuta energias negativas em positivas ao redor.' },
  { id: '29', name: 'Copo de Bambu Sustentável Zen', price: 'R$ 42,00', iconPlaceholder: '🎍', description: 'Bebidas com consciência ecológica e toque natural.' },
  { id: '30', name: 'Kit Óleos Essenciais Básicos (Lavanda, Limão, Menta)', price: 'R$ 99,90', iconPlaceholder: '🧪', description: 'Inicie na aromaterapia com os óleos essenciais.' },
  { id: '31', name: 'Toalha de Yoga Antiderrapante Microfibra', price: 'R$ 89,00', iconPlaceholder: '🧖‍♀️', description: 'Absorção e aderência extra para práticas intensas.' },
  { id: '32', name: 'Estátua Ganesha Removedor de Obstáculos', price: 'R$ 130,00', iconPlaceholder: '🐘', description: 'Atraia prosperidade e remova barreiras do caminho.' },
  { id: '33', name: 'Sabonete Artesanal Energizante de Alecrim', price: 'R$ 22,00', iconPlaceholder: '🧼', description: 'Limpeza e renovação com aroma estimulante.' },
  { id: '34', name: 'Mandala Decorativa de Parede Entalhada', price: 'R$ 180,00', iconPlaceholder: '☸️', description: 'Símbolo de harmonia e equilíbrio para seu lar.' },
  { id: '35', name: 'Chá Energizante de Gengibre com Limão', price: 'R$ 31,50', iconPlaceholder: '🍋', description: 'Impulso natural para começar bem o seu dia.' },
  { id: '36', name: 'Bloco de Yoga em EVA de Alta Densidade', price: 'R$ 35,00', iconPlaceholder: '🧱', description: 'Suporte e alinhamento para posturas de yoga.' },
  { id: '37', name: 'Colar Difusor Pessoal para Aromaterapia', price: 'R$ 79,00', iconPlaceholder: '🧿', description: 'Leve seus aromas favoritos sempre com você.' },
  { id: '38', name: 'Livro: Mindfulness - Atenção Plena no Dia a Dia', price: 'R$ 62,00', iconPlaceholder: '🧠', description: 'Técnicas para viver o presente com mais consciência.' },
  { id: '39', name: 'Incensário Cascata Fumaça Invertida Buda', price: 'R$ 115,00', iconPlaceholder: '🌬️', description: 'Efeito visual relaxante com sua fumaça sagrada.' },
  { id: '40', name: 'Pedra Ametista Drusa - Transmutação e Paz', price: 'R$ 70,00', iconPlaceholder: '💜', description: 'Poderoso cristal de proteção e espiritualidade.' },
  { id: '41', name: 'Cinto de Yoga em Algodão Orgânico', price: 'R$ 40,00', iconPlaceholder: '🎗️', description: 'Auxilia no alongamento e aprofundamento das posturas.' },
  { id: '42', name: 'Vaso de Cerâmica Artesanal Minimalista', price: 'R$ 95,00', iconPlaceholder: '🏺', description: 'Elegância e simplicidade para suas plantas e flores.' },
  { id: '43', name: 'Spray de Ambiente Lavanda e Camomila', price: 'R$ 58,00', iconPlaceholder: '💤', description: 'Crie uma atmosfera de calma antes de dormir.' },
  { id: '44', name: 'Pulseira de Jaspe Vermelho - Vitalidade', price: 'R$ 55,00', iconPlaceholder: '❤️‍🔥', description: 'Energia, força e coragem para seus desafios.' },
  { id: '45', name: 'Caixa de Chás Sortidos Bem-Estar', price: 'R$ 75,00', iconPlaceholder: '🎁', description: 'Uma seleção de chás para diferentes momentos do dia.' },
  { id: '46', name: 'Filtro dos Sonhos Artesanal com Penas', price: 'R$ 60,00', iconPlaceholder: '🕸️', description: 'Proteção e bons sonhos segundo a tradição indígena.' },
  { id: '47', name: 'Almofada Térmica de Sementes Aromática', price: 'R$ 48,00', iconPlaceholder: '♨️', description: 'Alívio de tensões musculares com calor e aroma.' },
  { id: '48', name: 'Óleo Vegetal de Coco Extra Virgem (Uso Cosmético)', price: 'R$ 38,00', iconPlaceholder: '🥥', description: 'Hidratação natural para pele e cabelos radiantes.' },
  { id: '49', name: 'Caderno Pontilhado para Bullet Journal Zen', price: 'R$ 52,00', iconPlaceholder: '📝', description: 'Organize sua vida com criatividade e intenção.' },
  { id: '50', name: 'Mini Jardim Zen de Mesa com Areia e Pedras', price: 'R$ 88,00', iconPlaceholder: '🏜️', description: 'Um refúgio de tranquilidade para sua mesa de trabalho.' },
  { id: '51', name: 'Tornozeleira Indiana com Guizos Delicados', price: 'R$ 45,00', iconPlaceholder: '🔔', description: 'Charme e sonoridade suave para seus passos.' },
  { id: '52', name: 'Baralho de Tarot Rider Waite Clássico', price: 'R$ 110,00', iconPlaceholder: '🃏', description: 'Ferramenta de autoconhecimento e orientação espiritual.' },
  { id: '53', name: 'Pedra Olho de Tigre - Coragem e Proteção', price: 'R$ 39,00', iconPlaceholder: '🐅', description: 'Afasta energias negativas e fortalece a intuição.' },
  { id: '54', name: 'Spray Aurico Limpeza Energética 7 Ervas', price: 'R$ 62,00', iconPlaceholder: '🌿✨', description: 'Purifique seu campo energético e eleve sua vibração.' },
  { id: '55', name: 'Caneca Personalizada "Gratidão Transforma"', price: 'R$ 35,00', iconPlaceholder: '☕️', description: 'Comece o dia com uma mensagem positiva e inspiradora.' },
  { id: '56', name: 'Manta Xale Indiano Leve Multiuso', price: 'R$ 99,00', iconPlaceholder: '🧣', description: 'Conforto e estilo para meditação ou como acessório.' },
  { id: '57', name: 'Sais de Banho Relaxantes de Eucalipto e Hortelã', price: 'R$ 42,00', iconPlaceholder: '🛀', description: 'Experiência de spa em casa para renovar as energias.' },
  { id: '58', name: 'Sino dos Ventos Bambu Som Suave', price: 'R$ 79,00', iconPlaceholder: '🎐', description: 'Melodia relaxante para varandas e jardins.' },
  { id: '59', name: 'Kit Mini Velas Aromáticas (Prosperidade, Amor, Paz)', price: 'R$ 65,00', iconPlaceholder: '🕯️🕯️🕯️', description: 'Intencione seus desejos com aromas específicos.' },
  { id: '60', name: 'Livro: "O Poder do Agora" por Eckhart Tolle', price: 'R$ 55,00', iconPlaceholder: '📖', description: 'Um guia para a iluminação espiritual e paz interior.' },
  { id: '61', name: 'Calça de Yoga Confortável em Viscose', price: 'R$ 120,00', iconPlaceholder: '👖', description: 'Liberdade de movimento e conforto para sua prática.' },
  { id: '62', name: 'Porta Incenso de Madeira Artesanal Folha', price: 'R$ 28,00', iconPlaceholder: '🍂', description: 'Suporte seguro e elegante para seus incensos.' },
  { id: '63', name: 'Chá de Hibisco Orgânico Antioxidante', price: 'R$ 27,00', iconPlaceholder: '🌺', description: 'Saboroso e rico em benefícios para a saúde.' },
  { id: '64', name: 'Máscara de Dormir Confortável com Ervas', price: 'R$ 49,00', iconPlaceholder: '😴', description: 'Bloqueio de luz e aroma relaxante para um sono profundo.' },
  { id: '65', name: 'Pêndulo de Cristal para Radiestesia', price: 'R$ 59,00', iconPlaceholder: '⚖️', description: 'Instrumento para medir e harmonizar energias.' },
  { id: '66', name: 'Escova Corporal de Cerdas Naturais Seca', price: 'R$ 53,00', iconPlaceholder: '🖌️', description: 'Estimula a circulação e esfolia a pele suavemente.' },
  { id: '67', name: 'Adorno de Porta Olho Grego Proteção', price: 'R$ 33,00', iconPlaceholder: '🧿🚪', description: 'Amuleto tradicional contra mau-olhado e inveja.' },
  { id: '68', name: 'Roll-on de Óleos Essenciais Foco e Concentração', price: 'R$ 47,00', iconPlaceholder: '🎯', description: 'Mix de aromas para clareza mental e produtividade.' },
  { id: '69', name: 'Tapete Redondo Mandala para Meditação', price: 'R$ 165,00', iconPlaceholder: '🧘‍♂️', description: 'Espaço sagrado e inspirador para sua prática meditativa.' },
  { id: '70', name: 'Cristal Citrino - Prosperidade e Sucesso', price: 'R$ 50,00', iconPlaceholder: '🌟', description: 'Atrai abundância, alegria e energias positivas.' },
  { id: '71', name: 'Difusor de Aromas para Carro com Pingente', price: 'R$ 43,00', iconPlaceholder: '🚗💨', description: 'Aromaterapia em movimento para viagens tranquilas.' },
  { id: '72', name: 'Livro de Colorir Antiestresse Mandalas', price: 'R$ 39,00', iconPlaceholder: '🎨', description: 'Relaxe e explore sua criatividade com belas mandalas.' },
  { id: '73', name: 'Pingente Árvore da Vida em Prata', price: 'R$ 89,00', iconPlaceholder: '🌳', description: 'Símbolo de conexão, crescimento e força vital.' },
  { id: '74', name: 'Sabonete Líquido Artesanal de Verbena', price: 'R$ 36,00', iconPlaceholder: '🧴', description: 'Limpeza suave com aroma cítrico e revigorante.' },
  { id: '75', name: 'Kit Palo Santo com Incensário de Cerâmica', price: 'R$ 78,00', iconPlaceholder: '🪵🏺', description: 'Conjunto completo para purificação e bem-estar.' },
  { id: '76', name: 'Almofada de Olhos com Linhaça e Lavanda', price: 'R$ 35,00', iconPlaceholder: '😌', description: 'Relaxamento profundo para os olhos e a mente.' },
  { id: '77', name: 'Chá Verde Orgânico Especial (Folhas Soltas)', price: 'R$ 40,00', iconPlaceholder: '🌿🍵', description: 'Rico em antioxidantes, para energia e vitalidade.' },
  { id: '78', name: 'Estátua de Shiva Nataraja Dançarino Cósmico', price: 'R$ 250,00', iconPlaceholder: '🕉️', description: 'Símbolo da criação, destruição e renovação do universo.' },
  { id: '79', name: 'Cumbuca de Cerâmica Artesanal para Chá', price: 'R$ 68,00', iconPlaceholder: '🥣', description: 'Aprecie seu chá em uma peça única e especial.' },
  { id: '81', name: 'Chá Branco Orgânico Celestial', price: 'R$ 38,50', iconPlaceholder: '🕊️', description: 'Delicadeza e pureza em cada gole, rico em antioxidantes.' },
  { id: '82', name: 'Spray Bucal Refrescante Menta e Hortelã', price: 'R$ 28,00', iconPlaceholder: '👄', description: 'Hálito fresco e natural para momentos de clareza.' },
  { id: '83', name: 'Pingente Difusor Pessoal em Aço Inox', price: 'R$ 95,00', iconPlaceholder: '💠', description: 'Leve a aromaterapia com elegância e durabilidade.' },
  { id: '84', name: 'Kit Massagem Gua Sha Quartzo Rosa Facial', price: 'R$ 115,00', iconPlaceholder: '💆‍♀️', description: 'Técnica milenar para uma pele revitalizada e relaxada.' },
  { id: '85', name: 'Livro: "A Arte da Simplicidade" Dominique Loreau', price: 'R$ 65,00', iconPlaceholder: '📖✨', description: 'Inspiração para uma vida mais leve e significativa.' },
  { id: '86', name: 'Bolsa Ecológica "Namastê" em Algodão Cru', price: 'R$ 49,00', iconPlaceholder: '🛍️', description: 'Carregue seus pertences com intenção e estilo consciente.' },
  { id: '87', name: 'Pedra Sodalita - Clareza Mental e Intuição', price: 'R$ 42,00', iconPlaceholder: '🧠🌌', description: 'Estimula o pensamento lógico e a percepção intuitiva.' },
  { id: '88', name: 'Óleo de Massagem Relaxante Lavanda e Camomila', price: 'R$ 68,00', iconPlaceholder: '💆‍♂️', description: 'Deslizamento suave para uma massagem profundamente calmante.' },
  { id: '89', name: 'Pôster Decorativo Frase Inspiradora Zen', price: 'R$ 35,00', iconPlaceholder: '🖼️', description: 'Decore seu espaço com palavras que elevam a alma.' },
  { id: '90', name: 'Incenso Nag Champa Original (Caixa)', price: 'R$ 29,90', iconPlaceholder: '🌸👃', description: 'Aroma clássico indiano para meditação e relaxamento.' },
  { id: '91', name: 'Meias de Yoga Antiderrapantes com Dedos', price: 'R$ 45,00', iconPlaceholder: '👣', description: 'Aderência e liberdade para seus pés durante a prática.' },
  { id: '92', name: 'Estátua Pequena Monge Meditando (Trio)', price: 'R$ 79,00', iconPlaceholder: '🧘‍♂️🧘‍♂️🧘‍♂️', description: 'Pequenos monges para inspirar paz em qualquer cantinho.' },
  { id: '93', name: 'Blend de Chás Detox Revigorante', price: 'R$ 33,00', iconPlaceholder: '🌿💧', description: 'Mistura de ervas para limpar o organismo e renovar.' },
  { id: '94', name: 'Pulseira de Contas de Madeira Sândalo', price: 'R$ 58,00', iconPlaceholder: '🪵📿', description: 'Aroma suave e natural, promove calma e clareza.' },
  { id: '95', name: 'Caderneta Artesanal Capa Bordada', price: 'R$ 60,00', iconPlaceholder: '📒🧵', description: 'Para anotações, desenhos ou como diário pessoal.' },
  { id: '96', name: 'Sino Pin Tibetano (Tingsha) Autêntico', price: 'R$ 129,00', iconPlaceholder: '🔔🔔', description: 'Som claro e vibrante para marcar início/fim de meditação.' },
  { id: '97', name: 'Óleo Essencial de Laranja Doce Alegria', price: 'R$ 32,00', iconPlaceholder: '🍊', description: 'Aroma cítrico que eleva o humor e traz leveza.' },
  { id: '98', name: 'Caixa Porta-Jóias/Objetos Indiana Entalhada', price: 'R$ 105,00', iconPlaceholder: '🗃️', description: 'Guarde seus tesouros com arte e significado.' },
  { id: '99', name: 'Amuleto Hamsá (Mão de Fátima) com Olho Grego', price: 'R$ 48,00', iconPlaceholder: '✋🧿', description: 'Proteção contra energias negativas e sorte.' },
  { id: '100', name: 'Infusor de Chá em Inox Formato Folha', price: 'R$ 25,00', iconPlaceholder: '🍂🍵', description: 'Prepare seus chás a granel com charme e praticidade.' },
  { id: '101', name: 'Pedra Pirita - Atração de Prosperidade', price: 'R$ 55,00', iconPlaceholder: '💰✨', description: 'Conhecida como "ouro de tolo", atrai riqueza e sucesso.' },
  { id: '102', name: 'Sabonete Líquido Glicerinado Erva Doce', price: 'R$ 34,00', iconPlaceholder: '🌿🧴', description: 'Limpeza suave e perfume delicado para suas mãos.' },
  { id: '103', name: 'Turmalina Negra Bruta - Proteção Energética Forte', price: 'R$ 60,00', iconPlaceholder: '🖤🛡️', description: 'Poderosa pedra de proteção contra energias densas.' },
  { id: '104', name: 'Pantufa Confortável "Zen Life"', price: 'R$ 75,00', iconPlaceholder: '👟😌', description: 'Conforto e aconchego para seus momentos de descanso.' },
  { id: '105', name: 'Jogo Americano Redondo Mandala Colorida', price: 'R$ 40,00', iconPlaceholder: '�️☸️', description: 'Leve harmonia e cor para suas refeições.' },
  { id: '106', name: 'Livro: "O Milagre da Manhã" por Hal Elrod', price: 'R$ 58,00', iconPlaceholder: '☀️📖', description: 'Transforme suas manhãs e sua vida com 6 hábitos.' },
  { id: '107', name: 'Vela Aromática de Canela e Maçã', price: 'R$ 52,00', iconPlaceholder: '🍎🕯️', description: 'Aroma acolhedor e estimulante para o ambiente.' },
  { id: '108', name: 'Chaveiro Mini Japamala 27 Contas', price: 'R$ 39,00', iconPlaceholder: '🔑📿', description: 'Um lembrete de mindfulness para levar com você.' },
  { id: '109', name: 'Spray de Travesseiro Bons Sonhos (Lavanda e Bergamota)', price: 'R$ 65,00', iconPlaceholder: '🛌💤', description: 'Aromas relaxantes para uma noite de sono reparadora.' },
  { id: '110', name: 'Capa de Almofada Indiana Bordada Elefante', price: 'R$ 88,00', iconPlaceholder: '🐘🛋️', description: 'Detalhes artesanais que trazem sorte e sabedoria.' },
  { id: '111', name: 'Rolo Massageador Facial de Jade', price: 'R$ 70,00', iconPlaceholder: '💚💆', description: 'Estimula a circulação e promove o relaxamento facial.' },
  { id: '112', name: 'Kit Incenso Cone Cascata com 5 Aromas', price: 'R$ 95,00', iconPlaceholder: '🌬️👃', description: 'Variedade de fragrâncias para seu incensário cascata.' },
  { id: '113', name: 'Óleo Essencial de Patchouli Concentração', price: 'R$ 43,00', iconPlaceholder: '🌿🧘', description: 'Aroma terroso que aterra e ajuda na meditação.' },
  { id: '114', name: 'Copo Térmico Mantra "Eu Sou Luz"', price: 'R$ 89,90', iconPlaceholder: '🥤✨', description: 'Mantenha sua bebida na temperatura ideal com inspiração.' },
  { id: '115', name: 'Pedra Quartzo Verde - Saúde e Bem-Estar', price: 'R$ 40,00', iconPlaceholder: '💚🌿', description: 'Promove equilíbrio físico, mental e emocional.' },
  { id: '116', name: 'Buda Cego, Surdo e Mudo (Sabedoria)', price: 'R$ 99,00', iconPlaceholder: '🙈🙉🙊', description: 'Lembrete para não ver, não ouvir e não falar o mal.' },
  { id: '117', name: 'Chá de Erva Cidreira Orgânico Relaxante', price: 'R$ 30,00', iconPlaceholder: '🍋🍵', description: 'Calmante natural para aliviar o estresse do dia a dia.' },
  { id: '118', name: 'Pulseira shamballa com Cristais Swarovski', price: 'R$ 120,00', iconPlaceholder: '✨💎', description: 'Brilho e energia positiva em um acessório elegante.' },
  { id: '119', name: 'Miniatura Torre Zen de Pedras Empilhadas', price: 'R$ 55,00', iconPlaceholder: '🪨⚖️', description: 'Símbolo de equilíbrio e paciência para sua decoração.' },
  { id: '120', name: 'Aromatizador Elétrico de Tomada Bivolt', price: 'R$ 60,00', iconPlaceholder: '🔌💨', description: 'Prático para difundir óleos essenciais no ambiente.' },
  { id: '121', name: 'Escova de Cabelo de Bambu Antiestática', price: 'R$ 48,00', iconPlaceholder: '🎋梳', description: 'Massageia o couro cabeludo e desembaraça suavemente.' },
  { id: '122', name: 'Livro: "As Quatro Nobres Verdades" Dalai Lama', price: 'R$ 70,00', iconPlaceholder: '☸️📚', description: 'Ensinamentos fundamentais do budismo para a vida.' },
  { id: '123', name: 'Colar com Pingente Flor de Lótus Vazado', price: 'R$ 79,00', iconPlaceholder: '🌸💍', description: 'Símbolo de pureza espiritual e renascimento.' },
  { id: '124', name: 'Pedra Água Marinha - Calmante e Comunicação', price: 'R$ 65,00', iconPlaceholder: '💧🗣️', description: 'Acalma a mente e facilita a expressão clara.' },
  { id: '125', name: 'Saquinho de Algodão para Ervas Aromáticas', price: 'R$ 15,00', iconPlaceholder: '🌿🛍️', description: 'Ideal para sachês perfumados em gavetas e armários.' },
  { id: '126', name: 'Tapeçaria de Parede Indiana Om Místico', price: 'R$ 130,00', iconPlaceholder: '🕉️🖼️', description: 'Decoração vibrante com o som sagrado do universo.' },
  { id: '127', name: 'Caneca com Infusor e Tampa "Tea Time"', price: 'R$ 92,00', iconPlaceholder: '☕⏳', description: 'Tudo o que você precisa para um chá perfeito e prático.' },
  { id: '128', name: 'Óleo Vegetal de Semente de Uva (Hidratante)', price: 'R$ 36,00', iconPlaceholder: '🍇💧', description: 'Leve e de rápida absorção para a pele e cabelos.' },
  { id: '129', name: 'Incensário de Cerâmica Artesanal Gota', price: 'R$ 50,00', iconPlaceholder: '💧🪵', description: 'Design elegante para queimar seus incensos com segurança.' },
  { id: '130', name: 'Baralho Cigano Lenormand Clássico', price: 'R$ 85,00', iconPlaceholder: '💃🃏', description: 'Oráculo tradicional para orientação e autoconhecimento.' },
  { id: '131', name: 'Limpador de Língua de Cobre Ayurvédico', price: 'R$ 40,00', iconPlaceholder: '👅✨', description: 'Para higiene bucal completa e remoção de toxinas.' },
  { id: '132', name: 'Chá Rooibos Orgânico (Chá Vermelho Africano)', price: 'R$ 37,00', iconPlaceholder: '🇿🇦🍵', description: 'Sem cafeína, sabor adocicado e rico em antioxidantes.' },
  { id: '133', name: 'Vela de Massagem Hidratante Karité e Lavanda', price: 'R$ 75,00', iconPlaceholder: '🕯️👐', description: 'Cera morna que se transforma em óleo de massagem nutritivo.' },
  { id: '134', name: 'Móbile Mensageiro dos Ventos com Pedras Naturais', price: 'R$ 98,00', iconPlaceholder: '🎶💎', description: 'Som harmonioso e beleza das pedras para seu lar.' },
  { id: '135', name: 'Cinto Faixa Elástico para Yoga e Alongamento', price: 'R$ 55,00', iconPlaceholder: '🤸‍♀️🎗️', description: 'Aumente sua flexibilidade e alcance em posturas.' },
  { id: '136', name: 'Pedra Obsidiana Negra - Escudo Protetor', price: 'R$ 49,00', iconPlaceholder: '🖤🛡️', description: 'Remove energias negativas e promove o autoconhecimento.' },
  { id: '137', name: 'Adesivo Decorativo de Parede Árvore da Vida', price: 'R$ 68,00', iconPlaceholder: '🌳✨', description: 'Transforme seu ambiente com este símbolo de conexão.' },
  { id: '138', name: 'Livro: "Comunicação Não-Violenta" Marshall Rosenberg', price: 'R$ 62,00', iconPlaceholder: '🗣️❤️', description: 'Técnicas para relacionamentos mais empáticos e eficazes.' },
  { id: '139', name: 'Kit Mini Budas da Sorte (Riqueza, Saúde, Amor)', price: 'R$ 88,00', iconPlaceholder: '💰❤️‍🩹❤️', description: 'Pequenas estátuas para atrair boas energias específicas.' },
  { id: '140', name: 'Óleo Essencial de Capim Limão Revitalizante', price: 'R$ 37,00', iconPlaceholder: '🌿🍋', description: 'Aroma cítrico que estimula a mente e alivia o cansaço.' },
  { id: '141', name: 'Garrafa Térmica Inox Estampa Mandala', price: 'R$ 110,00', iconPlaceholder: '🌡️☸️', description: 'Mantenha suas bebidas quentes ou frias com estilo zen.' },
  { id: '142', name: 'Pedra Cornalina - Energia Criativa e Vitalidade', price: 'R$ 46,00', iconPlaceholder: '🧡🔥', description: 'Estimula a criatividade, a coragem e a motivação.' },
  { id: '143', name: 'Porta Velas de Selenita Branca Torre', price: 'R$ 70,00', iconPlaceholder: '🤍🕯️', description: 'Ilumine e purifique o ambiente com a energia da selenita.' },
  { id: '144', name: 'Máscara Facial de Argila Verde Detox', price: 'R$ 39,00', iconPlaceholder: '🧖🌿', description: 'Limpeza profunda e controle da oleosidade da pele.' },
  { id: '145', name: 'Japamala 108 Contas de Sândalo Aromático', price: 'R$ 135,00', iconPlaceholder: '🪵📿👃', description: 'Contas perfumadas para uma meditação mais profunda.' },
  { id: '146', name: 'Chá de Gengibre com Especiarias Chai Latte Mix', price: 'R$ 42,00', iconPlaceholder: '🌶️☕', description: 'Mistura aromática e aquecedora para um chai delicioso.' },
  { id: '147', name: 'Anel Ajustável com Pedra da Lua Natural', price: 'R$ 95,00', iconPlaceholder: '💍🌙', description: 'Conecte-se com a intuição e a energia feminina.' },
  { id: '148', name: 'Difusor Pessoal para Carro Madeira e Feltro', price: 'R$ 58,00', iconPlaceholder: '🚗🌲', description: 'Aromaterapia natural e sutil para suas viagens.' },
  { id: '149', name: 'Prato Decorativo Cerâmica Símbolo Om', price: 'R$ 75,00', iconPlaceholder: '🍽️🕉️', description: 'Peça decorativa ou para oferendas, com energia sagrada.' },
  { id: '150', name: 'Livro de Orações e Mantras Universais', price: 'R$ 50,00', iconPlaceholder: '🙏🏽📖', description: 'Coletânea de preces e cantos para diversas tradições.' },
  { id: '151', name: 'Kit Jardinagem Zen Miniatura para Mesa', price: 'R$ 120,00', iconPlaceholder: '🪴🤏', description: 'Crie seu pequeno refúgio verde e relaxante no escritório.' },
  { id: '152', name: 'Óleo Essencial de Bergamota Alegria e Relaxamento', price: 'R$ 45,00', iconPlaceholder: '💚🍊', description: 'Cítrico floral que alivia a ansiedade e eleva o astral.' },
  { id: '153', name: 'Cofrinho Buda da Prosperidade Dourado', price: 'R$ 65,00', iconPlaceholder: '💰🗿', description: 'Incentive a poupança com um símbolo de abundância.' },
  { id: '154', name: 'Pedra Lepidolita - Calma e Transição', price: 'R$ 53,00', iconPlaceholder: '💜⚖️', description: 'Ajuda a aliviar o estresse e promove a serenidade em mudanças.' },
  { id: '155', name: 'Camiseta Algodão Orgânico Estampa "Be Kind"', price: 'R$ 89,00', iconPlaceholder: '👕💖', description: 'Vista uma mensagem positiva e inspire gentileza.' },
  { id: '156', name: 'Sais de Banho Efervescentes Lavanda e Rosas', price: 'R$ 48,00', iconPlaceholder: '🛁🌹', description: 'Transforme seu banho em um ritual de puro relaxamento.' },
  { id: '157', name: 'Mobile de Berço Artesanal Filtro dos Sonhos Baby', price: 'R$ 110,00', iconPlaceholder: '👶🕸️', description: 'Sonhos tranquilos e decoração encantadora para o bebê.' },
  { id: '158', name: 'Pulseira de Howlita Branca Paz e Serenidade', price: 'R$ 62,00', iconPlaceholder: '🤍🕊️', description: 'Promove a calma, paciência e um sono tranquilo.' },
  { id: '159', name: 'Roller de Massagem para Pés em Madeira Natural', price: 'R$ 59,00', iconPlaceholder: '🦶🪵', description: 'Alívio imediato para pés cansados e doloridos.' },
  { id: '160', name: 'Chá Mate Orgânico com Limão e Gengibre Energizante', price: 'R$ 35,00', iconPlaceholder: '🧉🍋', description: 'Combinação perfeita para dar um up na sua energia.' }
];